Repository d-o-p-e/inflearn-login-page-UI, pull requests merged in 2022-05, with the labels that each got.

#7 :lipstick: 버튼 컴포넌트 UI 생성
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Button/Button.js
  frontend/src/components/Button/Button.stories.js
  frontend/src/components/Button/styles.js
  frontend/src/stories/Button.js
Labels: :lipstick: lipstick

#9 :lipstick: input 컴포넌트 UI 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Input/Input.js
  frontend/src/components/Input/Input.stories.js
  frontend/src/components/Input/Style.js
Labels: haemin, :lipstick: lipstick

#10 💄 버튼 컴포넌트 생성
  frontend/src/App.js
  frontend/src/stories/Button.js
  frontend/src/stories/Button.stories.js
  frontend/src/stories/Button/Button.js
  frontend/src/stories/Button/Button.stories.js
  frontend/src/stories/Button/buttonCss.js
Labels: :lipstick: lipstick, juk2

#12 :lipstick: SocialLoginButton 컴포넌트 UI구현
  frontend/.eslintrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/SocialLoginButton/SocialLoginButton.js
  frontend/src/components/SocialLoginButton/SocialLoginButton.stories.js
  frontend/src/components/SocialLoginButton/Styles.js
  frontend/src/svg/apple.svg
  frontend/src/svg/facebook.svg
  frontend/src/svg/github.svg
  frontend/src/svg/google.svg
  frontend/src/svg/kakao.svg
Labels: haemin, :lipstick: lipstick

#16 💄버튼 컴포넌트 size에서 maxWidth 타입 추가
  frontend/src/App.js
  frontend/src/stories/Button/Button.stories.js
  frontend/src/stories/Button/buttonCss.js
Labels: :lipstick: lipstick, juk2

#17 💄 SocialAuthButton 컴포넌트 생성
  frontend/src/App.js
  frontend/src/assets/apple.svg
  frontend/src/assets/facebook.svg
  frontend/src/assets/github.svg
  frontend/src/assets/google.svg
  frontend/src/assets/kakaotalk.svg
  frontend/src/stories/SocialAuthButton/SocialAuthButton.js
  frontend/src/stories/SocialAuthButton/SocialAuthButton.stories.js
  frontend/src/stories/SocialAuthButton/SocialAuthButtonCss.js
Labels: :lipstick: lipstick, juk2

#19 🚑️버튼 컴포넌트 proptype 오류 해결
  frontend/src/stories/Button/Button.js
Labels: bug, juk2

#22 :lipstick: modal 컴포넌트 생성
  frontend/.eslintrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/modal/Modal.js
  frontend/src/components/modal/Modal.stories.js
  frontend/src/components/modal/Styles.js
Labels: haemin, :lipstick: lipstick

#23 💄modal 컴포넌트 생성
  frontend/.storybook/preview.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/assets/close.svg
  frontend/src/pages/Main/Main.js
  frontend/src/stories/Modal/Modal.js
  frontend/src/stories/Modal/Modal.stories.js
  frontend/src/stories/Modal/ModalCss.js
Labels: :lipstick: lipstick, juk2

#25 :lipstick: 회원가입 page 생성
  frontend/src/App.js
  frontend/src/pages/Main/Main.js
  frontend/src/pages/Register/Register.js
  frontend/src/pages/Register/RegisterCss.js
Labels: :lipstick: lipstick, juk2

#27 :lipstick: Input,Modal 컴포넌트 수정
  frontend/src/components/Input/Style.js
  frontend/src/components/modal/Modal.js
  frontend/src/components/modal/Modal.stories.js
Labels: bug, haemin, :lipstick: lipstick

#29 :lipstick: 로그인 Modal 창 구현
  frontend/src/assets/inflearnLogo.svg
  frontend/src/pages/Main/Main.js
  frontend/src/pages/Main/MainCss.js
  frontend/src/stories/Modal/ModalCss.js
Labels: :lipstick: lipstick, juk2

#30 로그인, 회원가입 페이지 생성
  frontend/src/App.js
  frontend/src/pages/Login/Login.js
  frontend/src/pages/Login/LoginStyle.js
  frontend/src/pages/SignUp/SignUp.js
  frontend/src/pages/SignUp/SignUpStyle.js
  frontend/src/svg/inflearn.svg
Labels: haemin, :sparkles: feature

#31 컴포넌트 px단위 에러 수정
  frontend/src/components/Button/styles.js
  frontend/src/components/Input/Style.js
  frontend/src/components/SocialLoginButton/Styles.js
  frontend/src/pages/Login/Login.js
  frontend/src/pages/Login/LoginStyle.js
Labels: haemin, :lipstick: lipstick
